/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/Home/': RouteRecordInfo<'/Home/', '/Home', Record<never, never>, Record<never, never>>,
    '/Home/AddNotePopup': RouteRecordInfo<'/Home/AddNotePopup', '/Home/AddNotePopup', Record<never, never>, Record<never, never>>,
    '/Home/AddTablePopup': RouteRecordInfo<'/Home/AddTablePopup', '/Home/AddTablePopup', Record<never, never>, Record<never, never>>,
    '/Home/Bill/': RouteRecordInfo<'/Home/Bill/', '/Home/Bill', Record<never, never>, Record<never, never>>,
    '/Home/Bill/CurrentBill': RouteRecordInfo<'/Home/Bill/CurrentBill', '/Home/Bill/CurrentBill', Record<never, never>, Record<never, never>>,
    '/Home/Bill/PreviousBill': RouteRecordInfo<'/Home/Bill/PreviousBill', '/Home/Bill/PreviousBill', Record<never, never>, Record<never, never>>,
    '/Home/Button/': RouteRecordInfo<'/Home/Button/', '/Home/Button', Record<never, never>, Record<never, never>>,
    '/Home/Button/BuzzerPopup': RouteRecordInfo<'/Home/Button/BuzzerPopup', '/Home/Button/BuzzerPopup', Record<never, never>, Record<never, never>>,
    '/Home/Button/CashOutPopup': RouteRecordInfo<'/Home/Button/CashOutPopup', '/Home/Button/CashOutPopup', Record<never, never>, Record<never, never>>,
    '/Home/Button/ChargeButtons': RouteRecordInfo<'/Home/Button/ChargeButtons', '/Home/Button/ChargeButtons', Record<never, never>, Record<never, never>>,
    '/Home/Button/Functions': RouteRecordInfo<'/Home/Button/Functions', '/Home/Button/Functions', Record<never, never>, Record<never, never>>,
    '/Home/Button/NumberButtons': RouteRecordInfo<'/Home/Button/NumberButtons', '/Home/Button/NumberButtons', Record<never, never>, Record<never, never>>,
    '/Home/Button/OpenItemPopup': RouteRecordInfo<'/Home/Button/OpenItemPopup', '/Home/Button/OpenItemPopup', Record<never, never>, Record<never, never>>,
    '/Home/Button/QuickAccess': RouteRecordInfo<'/Home/Button/QuickAccess', '/Home/Button/QuickAccess', Record<never, never>, Record<never, never>>,
    '/Home/ChargeToTablePopup': RouteRecordInfo<'/Home/ChargeToTablePopup', '/Home/ChargeToTablePopup', Record<never, never>, Record<never, never>>,
    '/Home/EndSalePopup': RouteRecordInfo<'/Home/EndSalePopup', '/Home/EndSalePopup', Record<never, never>, Record<never, never>>,
    '/Home/Footer': RouteRecordInfo<'/Home/Footer', '/Home/Footer', Record<never, never>, Record<never, never>>,
    '/Home/MenuItemVariationPopup': RouteRecordInfo<'/Home/MenuItemVariationPopup', '/Home/MenuItemVariationPopup', Record<never, never>, Record<never, never>>,
    '/Home/MenuPopup': RouteRecordInfo<'/Home/MenuPopup', '/Home/MenuPopup', Record<never, never>, Record<never, never>>,
    '/Home/NoSalePopup': RouteRecordInfo<'/Home/NoSalePopup', '/Home/NoSalePopup', Record<never, never>, Record<never, never>>,
    '/Home/PosChargePopup': RouteRecordInfo<'/Home/PosChargePopup', '/Home/PosChargePopup', Record<never, never>, Record<never, never>>,
    '/Home/ReceiptPopup': RouteRecordInfo<'/Home/ReceiptPopup', '/Home/ReceiptPopup', Record<never, never>, Record<never, never>>,
    '/Home/SplitBillPopup': RouteRecordInfo<'/Home/SplitBillPopup', '/Home/SplitBillPopup', Record<never, never>, Record<never, never>>,
    '/Home/TablePopup': RouteRecordInfo<'/Home/TablePopup', '/Home/TablePopup', Record<never, never>, Record<never, never>>,
    '/Home/TopNav': RouteRecordInfo<'/Home/TopNav', '/Home/TopNav', Record<never, never>, Record<never, never>>,
    '/Home/VoucherPaymentPopup': RouteRecordInfo<'/Home/VoucherPaymentPopup', '/Home/VoucherPaymentPopup', Record<never, never>, Record<never, never>>,
    '/Login': RouteRecordInfo<'/Login', '/Login', Record<never, never>, Record<never, never>>,
  }
}
